### ISSUE TITLE
Which drivers should be included with libmachine

### ISSUE THREAD

**Issue by afbjorklund** [minikube-machine/machine#1]
The previous list of drivers was mostly based on upstream blocking all additions.
And that there was no hardcoded list of which drivers were "allowed" to be used

```go
        CoreDrivers                  = []string{"amazonec2", "azure", "digitalocean",
                "exoscale", "generic", "google", "hyperv", "none", "openstack",
                "rackspace", "softlayer", "virtualbox", "vmwarefusion",
                "vmwarevcloudair", "vmwarevsphere"}
```

Probably some of the drivers should still be loaded from external grpc binaries.
This cuts down on library dependencies and general bloat, in the main binary?

I would suggest keeping these in:

generic (ssh)
none
virtualbox
qemu
kic

And moving these out:

**hyperkit**
**kvm** (libvirt)
hyperv
vmware
parallels

**Comment by medyagh** [comment]
by limbachine you mean the minikube-machine/machine ? 

and I am curious why qemu/vbox "keeping in" and "hyperv" and "hyperkit" is moving out ?

**Comment by afbjorklund** [comment]
Assuming here that we want to move the forked drivers, from minikube to libmachine:

hyperkit  kvm  none  qemu  ssh

And that we want to extend the virtual machine drivers, with the "kic" driver for containers

kic

**Comment by medyagh** [comment]
yes I would like to move as much code possible form minikube to minikube-machine (anything related to creating machine/drivers)

**Comment by afbjorklund** [comment]
> and I am curious why qemu/vbox "keeping in" and "hyperv" and "hyperkit" is moving out ?

they just run an external program, while the other ones are linking to powershell and C/C++ libraries

**Comment by medyagh** [comment]
I see makes sense, so vbox does not run vbox-manage ? but it uses a C/C++ library ? so you mean none of the code about Qemu would be in minikube-machine but infact in minikube project itself ?

I am on board with any solution that helps us test this new product easy, for example each time someone makes a change to this repo, there will be github action tests that will Create/Stop/Delete machines with all the drivers that Minikube-machine has

**Comment by medyagh** [comment]
per slack conversation with @afbjorklund I purpose, we start moving to use minikube-machine without any breaking changes, 
and long term will try to move the ISO itself to minikube-machine

**Comment by afbjorklund** [comment]
> I see makes sense, so vbox does not run vbox-manage ? but it uses a C/C++ library ?

It does use `VBoxManage`

**Comment by afbjorklund** [comment]
To make as little changes as possible, while still keeping the separation, these are the proposed git repositories:

`machine`
* errdriver
* fakedriver
* generic (ssh)
* hyperv
* none
* **qemu** (import from github.com/machine-drivers/docker-machine-driver-qemu)
* virtualbox

`machine-driver-kvm` (import from github.com/dhiltgen/docker-machine-kvm)
* kvm (libvirt)

`machine-driver-hyperkit` (import from github.com/machine-drivers/docker-machine-driver-hyperkit)
* hyperkit (xhyve)

`machine-driver-vmware` (import from github.com/machine-drivers/docker-machine-driver-vmware)
* vmware

`machine-driver-parallels` (import from github.com/Parallels/docker-machine-parallels)
* parallels

Then there needs to be a porting activity, to bring in generic2 and none2 and qemu2 and kvm2 and hyperkit2...

Those are the forked versions of the drivers used in minikube, that needs to cut off the minikube dependencies.

**Comment by afbjorklund** [comment]
Imported `drivers/qemu` now.

**Comment by afbjorklund** [comment]
Removed `drivers/qemu` again.

Should consider forking the old code, from github.com/machine-drivers/docker-machine-driver-qemu
